### ISSUE TITLE
/system/xbin/su detected on non rooted emulator (Android Q x86 with Google APIs)

### ISSUE THREAD

**Issue by Orbyt** [scottyab/rootbeer#119]
I've posted a similar question on StackOverflow, but will ask here as well incase this is unintended behavior.

One of the checks RootBeer performs is checking for the existence of `/system/xbin/su`.
 
I've noticed that emulators running an Android Q x86 (with *Google APIs*) image contain this file, and thus the root check returns `true`. However, emulators running an Android Q x86 image (with *Google Play*) do not contain `/system/xbin/su`, and thus the root check returns `false`.

These tests were performed with a Pixel 3 emulator utilizing the system images noted above.

Any idea why is this file present on the emulator with Android Q (Google APIs) but _not_ present on Android Q (with Google Play)? Should RootBeer's checks be modified to prevent this false positive (if it is, indeed, a false positive)?

Similarly, is checking for `/system/xbin/su` bound to result in false positives when attempting to detect root? Is that file often present on normal non-rooted devices?

**Comment by stealthcopter** [comment]
Hi @Orbyt 

Good question, this turned out to be fairly easy to test. I ran an emulator with Google play installed and launched a shell

```
adb shell
find / -name su 2>/dev/null
```

Mat

**Comment by stealthcopter** [comment]
Hi @Orbyt

Great question! It turned out to be fairly easy to figure out too :) I ran an emulator with Google play installed and launched a shell. Then I tried to run su and it was not found, a simple search also returned nothing.

```
adb shell
su
find / -name su 2>/dev/null
```

My conclusion is that these emulators with google play installed are not rooted, presumably this is to try to prevent tampering with the play store. Currently Rootbeer doesn't perform any emulator detections, but maybe this is something we can look at adding in the future.

Thanks

Mat

**Comment by Orbyt** [comment]
Hey @stealthcopter, thanks for the quick response. 

Any idea why `/system/xbin/su` _is_ present on system images with Google APIs?

**Comment by stealthcopter** [comment]
No problem. It's pretty useful as a developer to be able to have root access sometimes while trying to debug or test things. I think the emulators have always had su present for as long as I've been working with them. 

If it's an issue for you you could consider deleting the su binary from the emulator
