### ISSUE TITLE
Scoped Storage on Android 10

### ISSUE THREAD

**Issue by ytheekshana** [scottyab/rootbeer#134]
Does scoped storage on android 10+ affect the functionality of this library ??????

**Comment by stealthcopter** [comment]
From my limited understanding of I don't believe it will affect the library, as it seems to primarly affect how external storage is used, whereas we are looking for signs of root on the internal root partition. I'm pretty sure this will still be allowed as otherwise it'd probably stop many applications and the terminal on a phone from functioning.

However haven't tested this so would be great if someone else has more of an idea could chime in @scottyab maybe? or perhaps someone can test.

**Comment by stealthcopter** [comment]
Closing as it doesn't appear to be an issue. Tested on OnePlus 6T running 10.0
