### ISSUE TITLE
Device support removed Warning: Google Play-Store

### ISSUE THREAD

**Issue by chiragsharma991** [scottyab/rootbeer#143]
Why this implementation of code is showing error on play-store?

**Comment by stealthcopter** [comment]
This isn't enough information to figure out what's happening. Do you have any more details?

**Comment by chiragsharma991** [comment]
I added 'com.scottyab:rootbeer-lib:0.0.8' and checking root device like:

     RootBeer rootBeer = new RootBeer(this);
            if (rootBeer.isRooted()) {
            // perform any operation
            }

It seems working fine. but when i uploading my apk with this library, Google play store showing me one warning:

Device support removed Warning
Deactivation of this APK will result in your app being available for new installs on fewer types of devices.
TipIf : this is an unintended change, then retain this APK in the new release

I am not possible to find the root cause.

**Comment by stealthcopter** [comment]
Was that the only thing you changed when you updated the apk? This often happens when you update the min sdk version and some of the older phones that haven't been updated are no longer supported. I think if you click for more info it'll show you specifically which devices are no longer supported with your new update. It may be that because rootbeer have native libraries we're ruling out some weird or very old devices.

**Comment by stealthcopter** [comment]
Closed as stale, please re-open if you want to discuss in more detail.
