### ISSUE TITLE
master-SNAPSHOT broken

### ISSUE THREAD

**Issue by victor-flores1** [scottyab/rootbeer#235]
I'm unable to build my Android project.
I'm implementing this version 'com.github.scottyab:rootbeer:master-SNAPSHOT', but I'm getting this error:
"Could not resolve com.github.scottyab:rootbeer:master-SNAPSHOT"

I've verified that the master branch of rootbeer is broken, see the link:
https://jitpack.io/com/github/scottyab/rootbeer/master-0.1.0-ge14e074-10/build.log

**Comment by scottyab** [comment]
Hey @victor-flores1 , thanks for flaggin this. Likely due to my merge the other day of #229 which upgrades all of the things. Thanks for the build log it looks like it's an error signing the release, which makes sense as those details are private - I'm not sure what details it was using for the jitpack build previsiouly.  

Relying on the master branch via jitpack is not optimal can you switch to an release i.e https://jitpack.io/com/github/scottyab/rootbeer/0.1.0/? or better still the maven centeral version https://mvnrepository.com/artifact/com.scottyab/rootbeer-lib/0.1.0
  
I'm planning to publishing 0.1.1 to maven centeral by the end of the week after fixing the Circle CI issue.

**Comment by scottyab** [comment]
Also just thinking, I was planning to move the default/primary branch from `master` to `main` after the next release.

**Comment by victor-flores1** [comment]
@scottyab got it, thanks for getting back to me.

**Comment by nikonovmi** [comment]
@scottyab Thanks for getting back with the update! Looking forward to v0.1.1 :)

**Comment by NityaSantosh26** [comment]
@scottyab, Any update on v0.1.1 release? When can we expect the release?

**Comment by scottyab** [comment]
@nikonovmi I've had an issue with the new maven plugin where it's not attaching the source code and so maven central is blocking the release. I'll post an issue shortly as I look deeper into the issue

**Comment by scottyab** [comment]
created issue #236 to track the publishing issue I'm seeing.

**Comment by scottyab** [comment]
Closing as 0.1.1 is released and we should not be depending on master builds from jitpack.
