### ISSUE TITLE
Root detection failed on Motorolla Device Model XT1706

### ISSUE THREAD

**Issue by bytekode** [scottyab/rootbeer#39]
According to the same app provided on Google play store, it shows the device has busy box binary installed and all other checks are negative.
The sample didn't detected su binary and su management apps but still flag my device as rooted. How is that possible?

Feel free if any other details or logs are required.

Here is the device model I am referring to
http://www.gsmarena.com/motorola_moto_e3_power-8337.php

**Comment by stealthcopter** [comment]
Sorry can I just confirm your situation. 
Are you saying the Moto E3 has a busy box binary present? or that you have rooted your device and the sample fails to find any root management apps?

It would be useful if you could provide the logcat output when running the sample, thanks.

**Comment by bytekode** [comment]
@stealthcopter So my Moto E3 was not rooted and according to the sample app from Play Store it states that busy box binary was present on Moto E3.

I'll give you logs and screen shot some time later Today.

**Comment by stealthcopter** [comment]
It looks like some manufactures decide forget to remove the busybox binary from the system, or perhaps it is a conscious decision to do so for some unknown reason. Whilst this can be an annoyance creating a false positive for suggesting a device is rooted, it is still a sign of rooting nonetheless. If you want to avoid this problem in your own use of the library, you can simply remove the call to `checkForBusyBoxBinary()`.

I will suggest adding this to the readme so that this has more visiblity.

**Comment by bytekode** [comment]
Attached is the logs from Redmi note 3 and rootbeer is detecting busybox binary in case of Moto E3, Xiaomi Redmi Note 3 and One plus one. I think most of the manufacturers are adding busybox binary. Any thoughts?

[redmi_note_3_logs.txt](https://github.com/scottyab/rootbeer/files/867501/redmi_note_3_logs.txt)

**Comment by stealthcopter** [comment]
@bytekode As of commit 91e0a1137bb78c1e33e209ca0cd3f8946f8682fe we've added a new method for the library to have a new method `rootBeer.isRootedWithoutBusyBoxCheck()`, so that you can avoid false positives inside your application when using the library.

As for the sample app it makes sense to keep it as is, as this is merely an indication of root and states so at the bottom.
