### ISSUE TITLE
Crash on root native check

### ISSUE THREAD

**Issue by MPeti1** [scottyab/rootbeer#52]
I set rootcloak to hide root things from rootbeer sample app, and then the app crashes at root native check.
Notice: rw paths successfully detected.
OTP Smartbank app (Hungary) uses this root checking library, and it also crashes. Also, if i dont use rootcloak for smartbank, then it will not launch...
I bet the Hungarian OTP team not going to update the library in their app, so can you give me a quick fix how can i bypass the detection in an old version? You know, old versions not supported..
Me and many other users of the app thinks that OTP wants to decide if we want to use root, and it's a bad behavior.

Anyway, [here ](https://pastebin.com/7vrAbjcQ)is the log (OTP Smartbank crash when checking for root if rootcloak tries to hide it): 
And a [video ](https://youtu.be/2XfgqfzI4bg)(about the crashing sample app)

**Comment by ShadowWarrior0** [comment]
Did this crash occur on the latest release build, the latest master branch, or on another build?

**Comment by MPeti1** [comment]
Sorry, i don't know :/ I'm not a developer of the app, i only wanted to use it in my rooted phone. If you can provide a method to see it, i can provide it to you. Maybe if i decompile the app?

**Comment by stealthcopter** [comment]
As @MPeti1 suspects this is likely caused by an outdated version of the library included in the app in question. The library no longer crashes if the native root checking library cannot be loaded, but I think we still need to update the sample app on the Play store. The Hungarian OTP team should update the library used so they can provide better UX for when root is detected or suspected rather than just crashing. 

Also as we are the ones attempting to detect root we aren't really the best people to ask how to bypass our own work ;)

**Comment by ShadowWarrior0** [comment]
This was an issue that I fixed in the latest master. Once the next release of rootbeer is out, this will be fixed.
