### ISSUE TITLE
Further Root-Detections 

### ISSUE THREAD

**Issue by Iradj** [scottyab/rootbeer#54]
Are there other Root-Detections that RootBeer at the moment don't cover ?

**Comment by FunMan1995** [comment]
Maybe if you set it up that the app when running crates a randomly-generated name for a dummy app that actually runs all the functions for the checks through the dummy app and then deletes itself from the phone or tablet after sending the data to the original app? Cuz the root cooking methods so far only has Blacklist function not a whitelist function because a whitelist function can break route or disable root permissions if the root has not been encoded as an exception. meaning they would have to encode every version of root as an exception including tools like BusyBox and others and could not update until The Hider patch was updated. Another cool ideas to make it a module for root check for any app since it creates a dummy app to run the functions.

**Comment by djmk01** [comment]
:stuck_out_tongue_winking_eye:

**Comment by stealthcopter** [comment]
This is a bit vague, if anyone has specific checks they'd like to see implemented please open a new issue, thanks :)
