### ISSUE TITLE
UnsatisfiedLinkError 

### ISSUE THREAD

**Issue by yelhouti** [scottyab/rootbeer#55]
Hi,
thank you for the great lib,

I have an app that has compiled libs only for armeabi and x86, whne I run it it works well and all my .so are found when needed, when I add rootbeer-lib, to my dependencies, it adds other libs (including arm64) which i don't have .so for, my app starts runing in arm64 and fails to fails to find my lib and therefore craches.

how can I tell rootbeer to only provide .so for architectures I support?

Thank you

**Comment by scottyab** [comment]
Hey, I've had a similar issue which is down to the way Android loads native libs. For us the fix was to hassle the provider of the other native lib to support the other CPU architectures. So this issue doesn't feel like something rootbeer can or should fix. 

You access to the code so you could fork and remove arm64 support and build against that. 

Sorry prob not the answer you hoped for but thanks anyway for raising and using rootber.

**Comment by stealthcopter** [comment]
Can I just add a workaround I've done for one of my apps that might help:
@yelhouti There is a gradle library called soexcluder which can automatically remove .so files you specify as part of the build process. You could write this as your own gradle task, but this just makes it a lot easier:

https://github.com/Jween/android-soexcluder

**Comment by yelhouti** [comment]
thanks scottyab for confirming what I suspected, and thank you stealthcopter for provising the solution I was looking for :)
