### ISSUE TITLE
Android 9 false positive for check checkForBinary("su")

### ISSUE THREAD

**Issue by railanxisto** [scottyab/rootbeer#82]
Hi, 

My app is being accused of being a rooted device only on Android 9.
Is there already any known reason for that?

**Comment by paulkiren** [comment]
Same issue

**Comment by Prashanthlkv** [comment]
What are the devices(Nexus,Google Pixel) you guys are using?

**Comment by paulkiren** [comment]
YES Google Pixel

**Comment by litrik** [comment]
One of my users with a One Plus 5 running Android 9 has reported this as well.

**Comment by stealthcopter** [comment]
If you check the logs while running the test it will output why the false positive is being produced. I would imagine it's because the manufacturer has left a 'su' binary on the production build. In this case it isn't really a false positive, just a positive as the app is correctly identifying a root management tool. 

I don't have the devices in question to test, but I have tested on a Google Pixel XL and One Plus 6T without any false positives being flagged.

**Comment by stealthcopter** [comment]
In the upcoming release we've removed busybox from the default root checks, this should hopefully fix many of the problems with false positives. I'm closing this issue but please re-open if you get a false positive with 0.0.8 onwards.
Thanks!
